from __future__ import annotations

from typing import Protocol, Sequence

from src.graph.types import GraphEdge, GraphNode


class GraphStore(Protocol):
    def ping(self) -> bool: ...
    def ensure_schema(self) -> None: ...
    def upsert_nodes(self, nodes: Sequence[GraphNode]) -> None: ...
    def upsert_edges(self, edges: Sequence[GraphEdge]) -> None: ...
    def purge_collection(self, collection_id: str) -> None: ...
    def close(self) -> None: ...
